[package]
name = "devfest_noise_generator"
version = "1.0.0"
edition = "2021"
authors = ["Thomas Cami"]

[lib]
crate-type = ["cdylib"]

[dependencies]
nih_plug = { version = "*", git = "https://github.com/robbert-vdh/nih-plug" }
rand = "0.8.4"



